import javax.swing.JOptionPane;

public class TelaCadastro extends javax.swing.JFrame {
    
    public void removendoInformacoes() {
        loginUsuario.setText("");
        cpfUsuario.setText("");
        idadeUsuario.setText("");
        telefoneUsuario.setText("");
        senhaUsuario.setText("");
    }
    
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollBar1 = new javax.swing.JScrollBar();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        JLabel = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        JLabel3 = new javax.swing.JLabel();
        JLabel4 = new javax.swing.JLabel();
        JLabel5 = new javax.swing.JLabel();
        cidadeUsuario = new javax.swing.JComboBox<>();
        cpfUsuario = new javax.swing.JFormattedTextField();
        telefoneUsuario = new javax.swing.JFormattedTextField();
        loginUsuario = new javax.swing.JTextField();
        idadeUsuario = new javax.swing.JTextField();
        senhaUsuario = new javax.swing.JPasswordField();
        cadastrarUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        at = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");

        jPanel1.setBackground(new java.awt.Color(32, 27, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabel.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        JLabel.setForeground(new java.awt.Color(255, 255, 255));
        JLabel.setText("Usuário:");
        jPanel1.add(JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 20));

        JLabel2.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        JLabel2.setForeground(new java.awt.Color(255, 255, 255));
        JLabel2.setText("CPF:");
        jPanel1.add(JLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 20));

        JLabel3.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        JLabel3.setForeground(new java.awt.Color(255, 255, 255));
        JLabel3.setText("Idade:");
        jPanel1.add(JLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, 20));

        JLabel4.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        JLabel4.setForeground(new java.awt.Color(255, 255, 255));
        JLabel4.setText("Telefone:");
        jPanel1.add(JLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, 20));

        JLabel5.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        JLabel5.setForeground(new java.awt.Color(255, 255, 255));
        JLabel5.setText("Cidade:");
        jPanel1.add(JLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, 20));

        cidadeUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arapiraca", "Batalha", "Campo Alegre", "Coité do Noia", "Coruripe", "Craibas", "Delmiro Gouveia", "Jacaré dos Homens", "Jaramataia", "Junqueiro", "Maceió", "Maragogi", "Marechal Deodoro", "Pallet", "Palmeira do Índios", "Pão de Açúcar", "Penedo", "Piranhas", "Rio Largo", "São Miguel dos Campos", "Taquarana", "Teotônio Vilela", "Traipu", "União dos Palmares" }));
        cidadeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(cidadeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 180, 30));

        try {
            cpfUsuario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(cpfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 180, 30));

        try {
            telefoneUsuario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(telefoneUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 180, 30));
        jPanel1.add(loginUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 30));
        jPanel1.add(idadeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 180, 30));
        jPanel1.add(senhaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 180, 30));

        cadastrarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastrarUsuario.setText("Cadastrar");
        cadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 230, 30));

        jLabel2.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 620, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/usuarioCadastro.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, 140));

        jLabel4.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, 20));

        at.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        at.setForeground(new java.awt.Color(255, 255, 255));
        at.setText("Atendente");
        at.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atActionPerformed(evt);
            }
        });
        jPanel1.add(at, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarUsuarioActionPerformed
        String login = loginUsuario.getText();
        
        char[] aux = senhaUsuario.getPassword();
        String senha = new String(aux);
        
        String cpf = cpfUsuario.getText();
        int idade = Integer.parseInt(idadeUsuario.getText());
        String telefone = telefoneUsuario.getText();
        String cidade = cidadeUsuario.getSelectedItem().toString();
        
        boolean atendente;
        if(at.isSelected()){
            atendente = true;
        }
        else {
            atendente = false;
        }
        
        Usuario usuario = new Usuario(login, senha, cpf, idade, telefone, cidade, atendente);
        UsuarioDAO usuarioBanco = new UsuarioDAO();

        usuarioBanco.inserirUsuario(usuario);
        
        if(cidade.equals("Jaramataia")){
            JOptionPane.showMessageDialog(null, "Não aceitamos quem é de Jaramataia aqui!");
            System.exit(0);
        }
        if(cidade.equals("Pallet")){
            JOptionPane.showMessageDialog(null, "Gotta catch 'em all!");
        }
        else{
           JOptionPane.showMessageDialog(null, "Seja bem vindx, "+login+"!"); 
        }
        
        removendoInformacoes();
        
        dispose();
        
        if(atendente){
            String id = Integer.toString(usuario.getId());
            
            TelaAtendente t = new TelaAtendente(login, cpf, id);
            t.setVisible(true);
        }
        else{
            TelaUser t = new TelaUser();
            t.setVisible(true);
        }
        
    }//GEN-LAST:event_cadastrarUsuarioActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void atActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atActionPerformed
        
    }//GEN-LAST:event_atActionPerformed

    private void cidadeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeUsuarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel JLabel3;
    private javax.swing.JLabel JLabel4;
    private javax.swing.JLabel JLabel5;
    private javax.swing.JRadioButton at;
    private javax.swing.JButton cadastrarUsuario;
    private javax.swing.JComboBox<String> cidadeUsuario;
    private javax.swing.JFormattedTextField cpfUsuario;
    private javax.swing.JTextField idadeUsuario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField loginUsuario;
    private javax.swing.JPasswordField senhaUsuario;
    private javax.swing.JFormattedTextField telefoneUsuario;
    // End of variables declaration//GEN-END:variables
}